import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.player.allSimple.useQuery();

  const { mutate: createGame } = trpc.game.createGame.useMutation();

  const { mutate: joinLobby } = trpc.game.joinLobby.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          <span className="text-purple-300">Football</span> Guess
        </h1>
        <div className="flex gap-4">
          <button className="rounded-md bg-purple-500 p-4 font-bold text-white" onClick={() => createGame()}>
            Create
          </button>
          <button
            className="rounded-md bg-purple-400 p-4 font-bold text-white"
            onClick={() => joinLobby({ code: "_EHM" })}
          >
            Join
          </button>
        </div>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {isLoading && <h6>Loading...</h6>}
          <ul>
            {data?.map(({ id, name }) => (
              <li key={id}>{name}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
